// ---------------------------------------------------------------------------
// Author:        David Gilinsky
// File:          src/db/database.cpp
// Purpose:       Implementation of the MariaDB (libmariadb) database layer.
//                String inputs are escaped with mysql_real_escape_string;
//                numeric values are generated by this code, not by user input.
// Created:       2026-07-23
// Last Modified: 2026-07-23
// Version:       0.1.0
// License:       GPL-3.0-or-later
// ---------------------------------------------------------------------------
#include "database.hpp"

#include <mysql.h>

#include <cstdlib>
#include <fstream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace starbase::db {
namespace {

std::string opt_str(const char* p) { return p ? std::string(p) : std::string(); }

}  // namespace

struct Database::Impl {
    MYSQL* conn = nullptr;
};

DbConfig DbConfig::from_env() {
    DbConfig c;
    if (const char* v = std::getenv("SB_DB_HOST")) c.host = v;
    if (const char* v = std::getenv("SB_DB_PORT")) c.port = static_cast<uint16_t>(std::atoi(v));
    if (const char* v = std::getenv("SB_DB_USER")) c.user = v;
    if (const char* v = std::getenv("SB_DB_PASSWORD")) c.password = v;
    if (const char* v = std::getenv("SB_DB_NAME")) c.database = v;
    return c;
}

Database::Database(const DbConfig& cfg) : impl_(std::make_unique<Impl>()) {
    impl_->conn = mysql_init(nullptr);
    if (!impl_->conn) throw DbError("mysql_init failed (out of memory)");

    // Reconnect is deliberately off: a silent reconnect would drop session state
    // and mask a broken link. Callers handle failure explicitly.
    my_bool reconnect = 0;
    mysql_options(impl_->conn, MYSQL_OPT_RECONNECT, &reconnect);
    mysql_options(impl_->conn, MYSQL_SET_CHARSET_NAME, "utf8mb4");

    // CLIENT_MULTI_STATEMENTS lets apply_script() hand a whole .sql file to the
    // server, which parses it properly. Splitting on ';' in C++ would break on
    // semicolons inside string literals and comments.
    if (!mysql_real_connect(impl_->conn, cfg.host.c_str(), cfg.user.c_str(),
                            cfg.password.c_str(), cfg.database.c_str(), cfg.port,
                            nullptr, CLIENT_MULTI_STATEMENTS)) {
        const std::string err = mysql_error(impl_->conn);
        mysql_close(impl_->conn);
        impl_->conn = nullptr;
        throw DbError("cannot connect to " + cfg.user + "@" + cfg.host + ":" +
                      std::to_string(cfg.port) + "/" + cfg.database + ": " + err);
    }
}

Database::~Database() {
    if (impl_ && impl_->conn) mysql_close(impl_->conn);
}

std::string Database::server_version() const {
    return opt_str(mysql_get_server_info(impl_->conn));
}

std::string Database::escape(const std::string& s) const {
    std::string out(s.size() * 2 + 1, '\0');
    const unsigned long n =
        mysql_real_escape_string(impl_->conn, out.data(), s.c_str(), s.size());
    out.resize(n);
    return out;
}

int Database::apply_script(const std::string& path) {
    std::ifstream in(path);
    if (!in) throw DbError("cannot open SQL script: " + path);
    std::ostringstream ss;
    ss << in.rdbuf();
    const std::string sql = ss.str();
    if (sql.find_first_not_of(" \t\r\n") == std::string::npos)
        throw DbError("SQL script is empty: " + path);

    if (mysql_real_query(impl_->conn, sql.c_str(), sql.size()) != 0)
        throw DbError("applying " + path + ": " + mysql_error(impl_->conn));

    // Every result set must be consumed, or the connection is left unusable.
    int statements = 0;
    int status = 0;
    do {
        ++statements;
        if (MYSQL_RES* res = mysql_store_result(impl_->conn)) {
            mysql_free_result(res);
        } else if (mysql_field_count(impl_->conn) != 0) {
            throw DbError("applying " + path + " (statement " +
                          std::to_string(statements) + "): " + mysql_error(impl_->conn));
        }
        status = mysql_next_result(impl_->conn);
        if (status > 0)
            throw DbError("applying " + path + " (statement " +
                          std::to_string(statements + 1) + "): " + mysql_error(impl_->conn));
    } while (status == 0);

    return statements;
}

std::vector<Database::Row> Database::query(const std::string& sql) {
    if (mysql_real_query(impl_->conn, sql.c_str(), sql.size()) != 0)
        throw DbError(std::string("query: ") + mysql_error(impl_->conn), mysql_errno(impl_->conn));
    MYSQL_RES* res = mysql_store_result(impl_->conn);
    std::vector<Row> rows;
    if (res) {
        const unsigned int ncols = mysql_num_fields(res);
        while (MYSQL_ROW row = mysql_fetch_row(res)) {
            const unsigned long* lens = mysql_fetch_lengths(res);
            Row out;
            out.reserve(ncols);
            for (unsigned int c = 0; c < ncols; ++c) {
                if (row[c]) out.emplace_back(std::string(row[c], lens[c]));
                else out.emplace_back(std::nullopt);
            }
            rows.push_back(std::move(out));
        }
        mysql_free_result(res);
    } else if (mysql_field_count(impl_->conn) != 0) {
        throw DbError(std::string("query (result fetch): ") + mysql_error(impl_->conn));
    }
    return rows;
}

long long Database::exec(const std::string& sql) {
    if (mysql_real_query(impl_->conn, sql.c_str(), sql.size()) != 0)
        throw DbError(std::string("exec: ") + mysql_error(impl_->conn), mysql_errno(impl_->conn));
    return static_cast<long long>(mysql_insert_id(impl_->conn));
}

long long Database::affected_rows() const {
    return static_cast<long long>(mysql_affected_rows(impl_->conn));
}

bool Database::table_exists(const std::string& name) {
    const std::string q =
        "SELECT 1 FROM information_schema.tables WHERE table_schema = DATABASE() "
        "AND table_name = '" + escape(name) + "' LIMIT 1";
    if (mysql_real_query(impl_->conn, q.c_str(), q.size()) != 0)
        throw DbError(std::string("table_exists: ") + mysql_error(impl_->conn));
    MYSQL_RES* res = mysql_store_result(impl_->conn);
    const bool found = res && mysql_num_rows(res) > 0;
    if (res) mysql_free_result(res);
    return found;
}

std::vector<std::string> Database::tables() {
    const std::string q =
        "SELECT table_name FROM information_schema.tables "
        "WHERE table_schema = DATABASE() AND table_type = 'BASE TABLE' ORDER BY table_name";
    if (mysql_real_query(impl_->conn, q.c_str(), q.size()) != 0)
        throw DbError(std::string("tables: ") + mysql_error(impl_->conn));
    MYSQL_RES* res = mysql_store_result(impl_->conn);
    std::vector<std::string> out;
    if (res) {
        while (MYSQL_ROW row = mysql_fetch_row(res)) out.push_back(opt_str(row[0]));
        mysql_free_result(res);
    }
    return out;
}

int Database::schema_version() {
    if (!table_exists("schema_version")) return 0;
    const std::string q = "SELECT COALESCE(MAX(version), 0) FROM schema_version";
    if (mysql_real_query(impl_->conn, q.c_str(), q.size()) != 0)
        throw DbError(std::string("schema_version: ") + mysql_error(impl_->conn));
    MYSQL_RES* res = mysql_store_result(impl_->conn);
    int v = 0;
    if (res) {
        if (MYSQL_ROW row = mysql_fetch_row(res)) v = row[0] ? std::atoi(row[0]) : 0;
        mysql_free_result(res);
    }
    return v;
}

int Database::add_root(const std::string& label, const std::string& path,
                       const RootFields& f) {
    std::ostringstream cols, vals;
    cols << "label, path, path_hash";
    vals << "'" << escape(label) << "', '" << escape(path)
         << "', UNHEX(MD5('" << escape(path) << "'))";

    auto add_bool = [&](const char* name, const std::optional<bool>& v) {
        if (v) { cols << ", " << name; vals << ", " << (*v ? 1 : 0); }
    };
    auto add_int = [&](const char* name, const std::optional<int>& v) {
        if (v) { cols << ", " << name; vals << ", " << *v; }
    };
    auto add_str = [&](const char* name, const std::optional<std::string>& v) {
        if (v) { cols << ", " << name; vals << ", '" << escape(*v) << "'"; }
    };

    add_bool("enabled", f.enabled);
    add_bool("writable", f.writable);
    add_bool("case_sensitive", f.case_sensitive);
    add_str("watch_mode", f.watch_mode);
    add_int("scan_interval_s", f.scan_interval_s);
    add_int("settle_seconds", f.settle_seconds);
    add_str("fs_type", f.fs_type);
    add_str("ignore_globs", f.ignore_globs);

    const std::string q =
        "INSERT INTO roots (" + cols.str() + ") VALUES (" + vals.str() + ")";
    if (mysql_real_query(impl_->conn, q.c_str(), q.size()) != 0) {
        const unsigned int e = mysql_errno(impl_->conn);
        const std::string msg = mysql_error(impl_->conn);
        if (e == 1062)  // ER_DUP_ENTRY
            throw DbError("a root with that label or path already exists (" + msg + ")", e);
        throw DbError("add_root: " + msg, e);
    }
    return static_cast<int>(mysql_insert_id(impl_->conn));
}

namespace {

RootRow row_to_root(MYSQL_ROW row) {
    RootRow r;
    r.id               = row[0] ? std::atoi(row[0]) : 0;
    r.label            = opt_str(row[1]);
    r.path             = opt_str(row[2]);
    r.enabled          = row[3] && std::atoi(row[3]) != 0;
    r.writable         = row[4] && std::atoi(row[4]) != 0;
    r.case_sensitive   = row[5] && std::atoi(row[5]) != 0;
    r.watch_mode       = opt_str(row[6]);
    r.scan_interval_s  = row[7] ? std::atoi(row[7]) : 0;
    r.settle_seconds   = row[8] ? std::atoi(row[8]) : 0;
    r.ignore_globs     = opt_str(row[9]);
    r.fs_type          = opt_str(row[10]);
    r.last_scan_status = opt_str(row[11]);
    r.last_scan_end    = opt_str(row[12]);
    r.last_scan_error  = opt_str(row[13]);
    r.file_count       = row[14] ? std::atoll(row[14]) : 0;
    return r;
}

constexpr const char* kRootColumns =
    "id, label, path, enabled, writable, case_sensitive, watch_mode, "
    "scan_interval_s, settle_seconds, ignore_globs, fs_type, last_scan_status, "
    "last_scan_end, last_scan_error, file_count";

}  // namespace

std::vector<RootRow> Database::list_roots() {
    const std::string q =
        std::string("SELECT ") + kRootColumns + " FROM roots ORDER BY label";
    if (mysql_real_query(impl_->conn, q.c_str(), q.size()) != 0)
        throw DbError(std::string("list_roots: ") + mysql_error(impl_->conn));
    MYSQL_RES* res = mysql_store_result(impl_->conn);
    std::vector<RootRow> out;
    if (res) {
        while (MYSQL_ROW row = mysql_fetch_row(res)) out.push_back(row_to_root(row));
        mysql_free_result(res);
    }
    return out;
}

std::optional<RootRow> Database::find_root_by_label(const std::string& label) {
    const std::string q = std::string("SELECT ") + kRootColumns +
                          " FROM roots WHERE label = '" + escape(label) + "' LIMIT 1";
    if (mysql_real_query(impl_->conn, q.c_str(), q.size()) != 0)
        throw DbError(std::string("find_root_by_label: ") + mysql_error(impl_->conn));
    MYSQL_RES* res = mysql_store_result(impl_->conn);
    std::optional<RootRow> out;
    if (res) {
        if (MYSQL_ROW row = mysql_fetch_row(res)) out = row_to_root(row);
        mysql_free_result(res);
    }
    return out;
}

bool Database::update_root(const std::string& label, const RootFields& f) {
    std::vector<std::string> sets;
    auto set_bool = [&](const char* n, const std::optional<bool>& v) {
        if (v) sets.push_back(std::string(n) + " = " + (*v ? "1" : "0"));
    };
    auto set_int = [&](const char* n, const std::optional<int>& v) {
        if (v) sets.push_back(std::string(n) + " = " + std::to_string(*v));
    };
    auto set_str = [&](const char* n, const std::optional<std::string>& v) {
        if (v) sets.push_back(std::string(n) + " = '" + escape(*v) + "'");
    };

    set_bool("enabled", f.enabled);
    set_bool("writable", f.writable);
    set_bool("case_sensitive", f.case_sensitive);
    set_str("watch_mode", f.watch_mode);
    set_int("scan_interval_s", f.scan_interval_s);
    set_int("settle_seconds", f.settle_seconds);
    set_str("fs_type", f.fs_type);
    set_str("ignore_globs", f.ignore_globs);
    if (sets.empty()) return false;

    std::ostringstream q;
    q << "UPDATE roots SET ";
    for (size_t i = 0; i < sets.size(); ++i) q << (i ? ", " : "") << sets[i];
    q << " WHERE label = '" << escape(label) << "'";

    const std::string s = q.str();
    if (mysql_real_query(impl_->conn, s.c_str(), s.size()) != 0)
        throw DbError(std::string("update_root: ") + mysql_error(impl_->conn));
    return mysql_affected_rows(impl_->conn) > 0;
}

bool Database::remove_root(const std::string& label) {
    const std::string q = "DELETE FROM roots WHERE label = '" + escape(label) + "'";
    if (mysql_real_query(impl_->conn, q.c_str(), q.size()) != 0)
        throw DbError(std::string("remove_root: ") + mysql_error(impl_->conn));
    return mysql_affected_rows(impl_->conn) > 0;
}

}  // namespace starbase::db
