// ---------------------------------------------------------------------------
// Author:        David Gilinsky
// File:          src/pix/wbpp.cpp
// Purpose:       Implementation of the WBPP command-line renderer.
// Created:       2026-07-25
// Last Modified: 2026-07-25
// Version:       0.1.0
// License:       GPL-3.0-or-later
// ---------------------------------------------------------------------------
#include "wbpp.hpp"

#include <sstream>

namespace starbase::pix {
namespace {

// Single-quote a string for POSIX sh, closing and reopening around any embedded
// quote: it's  ->  'it'\''s'. Safe for paths with spaces, $, etc.
std::string sh_squote(const std::string& s) {
    std::string out = "'";
    for (char c : s) {
        if (c == '\'') out += "'\\''";
        else out += c;
    }
    out += "'";
    return out;
}

bool has_delimiter(const std::string& s) {
    return s.find(',') != std::string::npos || s.find('=') != std::string::npos;
}

}  // namespace

WbppPlan render(const std::string& job_root,
                const std::vector<std::string>& image_types,
                const WbppProfile& profile, bool load_only) {
    WbppPlan plan;
    plan.staging_root = job_root;
    plan.output_dir = profile.output_dir;
    plan.mode = load_only ? "loadOnly" : "automation";

    // The -r tokens, in the order WBPP reads them. The script path is the first
    // token; automationMode is mandatory for CLI operation.
    plan.params.push_back(profile.wbpp_script);
    plan.params.push_back("automationMode=true");

    // One recursive dir= per image-type subdirectory present in the tree. The
    // names are StarBase-generated (job-<id>/<type>), so they never carry a ','
    // or '=' that WBPP's argument split would choke on.
    for (const auto& t : image_types) {
        const std::string d = job_root + "/" + t;
        plan.dirs.push_back(d);
        plan.params.push_back("dir=" + d);
        if (has_delimiter(d))
            plan.warnings.push_back("staging path contains ',' or '=' which WBPP "
                                    "cannot parse: " + d);
    }

    if (!profile.output_dir.empty()) {
        plan.params.push_back("outputDirectory=" + profile.output_dir);
        if (has_delimiter(profile.output_dir))
            plan.warnings.push_back("output directory contains ',' or '=' which "
                                    "WBPP cannot parse: " + profile.output_dir);
    }

    plan.params.push_back(std::string("groupingKeywordsEnabled=") +
                          (profile.grouping_enabled ? "true" : "false"));
    if (profile.grouping_enabled && !profile.keywords.empty())
        plan.params.push_back("keywords=" + profile.keywords);
    plan.params.push_back("fitsCoordinateConvention=" +
                          std::to_string(profile.fits_convention));

    for (const auto& p : profile.extra_params)
        if (!p.empty()) plan.params.push_back(p);

    // loadOnly opens the dialog; headless automation runs and exits.
    if (load_only) plan.params.push_back("loadOnly");

    if (image_types.empty())
        plan.warnings.push_back("no image-type subdirectories: nothing to hand off");

    // Assemble the -r spec (tokens joined by commas) and the full command.
    std::string rspec;
    for (size_t i = 0; i < plan.params.size(); ++i)
        rspec += (i ? "," : "") + plan.params[i];

    std::ostringstream cmd;
    cmd << profile.pixinsight_sh << " -n --automation-mode "
        << "-r=" << sh_squote(rspec);
    // --force-exit only in headless mode; with loadOnly the GUI must stay up.
    if (!load_only) cmd << " --force-exit";
    plan.command = cmd.str();

    // A self-contained launcher the user can download and run from their
    // desktop session, where DISPLAY and PixInsight's per-user settings live.
    std::ostringstream sh;
    sh << "#!/usr/bin/env bash\n"
       << "# Generated by StarBase - PixInsight WBPP handoff (" << plan.mode << " mode).\n"
       << "# Run this from your desktop session; starbased has no display of its own.\n"
       << "set -euo pipefail\n\n";
    if (!plan.output_dir.empty())
        sh << "mkdir -p " << sh_squote(plan.output_dir) << "\n\n";
    sh << "echo 'Handing " << plan.dirs.size()
       << " staged frame set(s) to WBPP (" << plan.mode << ")...'\n"
       << "exec " << plan.command << "\n";
    plan.launcher = sh.str();

    return plan;
}

}  // namespace starbase::pix
